version: "2.0"
services:
  web:
    container_name: apache_server
    build:
       context: ./
       dockerfile: webserver
    ports:
       - "8088:80"
       - "4433:443"
    volumes:
      - ./:/var/www/html
#   restart: always
  mysql_db:
    image: mysql:latest
    container_name: mysql_server
#    ports:
#      - "33066:3306"
    environment:
      MYSQL_DATABASE: hello
      MYSQL_USER: hello
      MYSQL_PASSWORD: h3LL0
      MYSQL_ROOT_PASSWORD: hello
#   restart: always

#Note-: If you want to restart the docker container on system start up, uncomment the restart:always line.